baseURL = "http://example.org/"
languageCode = "en-us"
title = "Symphony Eco"
disableKinds = ["taxonomy", "taxonomyTerm"]


# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Our Experience"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Your Impact"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "The News"
        url     = "knowledge"
        weight  = 4
    [[menu.nav]]
        name    = "Let's Go!"
        url     = "contact"
        weight  = 5

# Site Params
[params]
    home = "Start"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Tesla's Awesome Hugo Site"
    author = "Christine Zierold & Aaron Pinto"
    keywords = "Consulting; Conservation;"
    # Google Analitycs
    googleAnalitycsID = "Your ID"
    facebookLink = "https://www.facebook.com/Symphony.Eco"
    instagramLink = "https://www.instagram.com/symphony.eco"
    twitterLink = "https://twitter.com/SymphonyEco"

    # Service Section On Homepage
    [params.service]
        enable  = true
        title   = "SSSSS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false