baseURL = "http://symphony.eco/"
languageCode = "en-us"
title = "Symphony ECO - Comprehensive Conservation Consulting"
summaryLength = "10"
paginate = 6
publishDir = "docs"


[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

[sitemap]

  filename = "sitemap.xml"



# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Our Passion"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Your Impact"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "The News"
        url     = "news"
        weight  = 4
    [[menu.nav]]
        name    = "Let's Chat!"
        url     = "contact"
        weight  = 5

# Site Params
[params]
    home = "Start"
    fav_icon ="images/favicon.ico"
    og_image = "images/og_image.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Symphony ECO creates Digital Strategies to grow the impact & visibility of eco-focused Government & Non-Government Organizations around the world"
    author = "Symphony ECO"
    keywords = "Consulting; Conservation; Environment;"
    # Google Analitycs
    googleAnalitycsID = "Your ID"
    facebookLink = "https://www.facebook.com/Symphony.Eco"
    instagramLink = "https://www.instagram.com/symphony.eco"
    twitterLink = "https://twitter.com/SymphonyEco"
    twitter ="@SymphonyEco"
    twitterhandle ="SymphonyEco"
    resizetiny ="900"
    resizesmall="1300"
    resizemedium="1900"
    resizelarge="2500"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook-f" 
link = "https://www.facebook.com/Symphony.Eco"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/SymphonyEco"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram" 
link = "https://www.instagram.com/symphony.eco"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin-in"
link = "#"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[markup.goldmark.renderer]
unsafe= true